/**
 * @summary metadata store mutations constants
 * @author Dominik Haas-Artho
 *
 * Created at     : 2019-10-23 16:34:51 
 * Last modified  : 2019-10-23 16:46:58
 *
 * This file is subject to the terms and conditions defined in
 * file 'LICENSE.txt', which is part of this source code package.
 */

export const BULK_LOAD_METADATAS_CONTENT = 'BULK_LOAD_METADATAS_CONTENT';
export const BULK_LOAD_METADATAS_CONTENT_SUCCESS = 'BULK_LOAD_METADATAS_CONTENT_SUCCESS';
export const BULK_LOAD_METADATAS_CONTENT_ERROR = 'BULK_LOAD_METADATAS_CONTENT_ERROR';

export const LOAD_METADATA_CONTENT_BY_ID = 'LOAD_METADATA_CONTENT_BY_ID';
export const LOAD_METADATA_CONTENT_BY_ID_SUCCESS = 'LOAD_METADATA_CONTENT_BY_ID_SUCCESS';
export const LOAD_METADATA_CONTENT_BY_ID_ERROR = 'LOAD_METADATA_CONTENT_BY_ID_ERROR';
export const CLEAN_CURRENT_METADATA = 'CLEAN_CURRENT_METADATA';

export const SEARCH_METADATA = 'SEARCH_METADATA';
export const SEARCH_METADATA_SUCCESS = 'SEARCH_METADATA_SUCCESS';
export const SEARCH_METADATA_ERROR = 'SEARCH_METADATA_ERROR';
export const CLEAR_SEARCH_METADATA = 'CLEAR_SEARCH_METADATA';

export const UPDATE_TAGS = 'UPDATE_TAGS';
export const UPDATE_TAGS_SUCCESS = 'UPDATE_TAGS_SUCCESS';
export const UPDATE_TAGS_ERROR = 'UPDATE_TAGS_ERROR';

export const FILTER_METADATA = 'FILTER_METADATA';
export const FILTER_METADATA_SUCCESS = 'FILTER_METADATA_SUCCESS';
export const FILTER_METADATA_ERROR = 'FILTER_METADATA_ERROR';

export const PIN_METADATA = 'PIN_METADATA';
export const CLEAR_PINNED_METADATA = 'CLEAR_PINNED_METADATA';
export const SET_DETAIL_PAGE_BACK_URL = 'SET_DETAIL_PAGE_BACK_URL';
export const SET_ABOUT_PAGE_BACK_URL = 'SET_ABOUT_PAGE_BACK_URL';
export const SET_VIRTUAL_LIST_INDEX = 'SET_VIRTUAL_LIST_INDEX';

export const METADATA_NAMESPACE = 'metadata';

export const LISTCONTROL_LIST_ACTIVE = 0;
export const LISTCONTROL_MAP_ACTIVE = 1;
export const LISTCONTROL_COMPACT_LAYOUT_ACTIVE = 2;
