export const LOAD_ALL_METADATA = 'LOAD_ALL_METADATA';
export const LOAD_ALL_METADATA_SUCCESS = 'LOAD_ALL_METADATA_SUCCESS';
export const LOAD_ALL_METADATA_ERROR = 'LOAD_ALL_METADATA_ERROR';

export const LOAD_METADATA_IDS = 'LOAD_METADATA_IDS';
export const LOAD_METADATA_IDS_SUCCESS = 'LOAD_METADATA_IDS_SUCCESS';
export const LOAD_METADATA_IDS_ERROR = 'LOAD_METADATA_IDS_ERROR';

export const LOAD_METADATAS_CONTENT = 'LOAD_METADATAS_CONTENT';
export const LOAD_METADATAS_CONTENT_SUCCESS = 'LOAD_METADATAS_CONTENT_SUCCESS';
export const LOAD_METADATAS_CONTENT_ERROR = 'LOAD_METADATAS_CONTENT_ERROR';

export const LOAD_METADATA_CONTENT_BY_ID = 'LOAD_METADATA_CONTENT_BY_ID';
export const LOAD_METADATA_CONTENT_BY_ID_SUCCESS = 'LOAD_METADATA_CONTENT_BY_ID_SUCCESS';
export const LOAD_METADATA_CONTENT_BY_ID_ERROR = 'LOAD_METADATA_CONTENT_BY_ID_ERROR';

export const SEARCH_METADATA = 'SEARCH_METADATA';
export const SEARCH_METADATA_SUCCESS = 'SEARCH_METADATA_SUCCESS';
export const SEARCH_METADATA_ERROR = 'SEARCH_METADATA_ERROR';

export const ADD_METADATA = 'ADD_METADATA';
export const ADD_TEST_METADATA = 'ADD_TEST_METADATA';

export const LOAD_ALL_TAGS = 'LOAD_ALL_TAGS';
export const LOAD_ALL_TAGS_SUCCESS = 'LOAD_ALL_TAGS_SUCCESS';
export const LOAD_ALL_TAGS_ERROR = 'LOAD_ALL_TAGS_ERROR';
