export const GET_ALL_METADATA = 'GET_ALL_METADATA';
export const GET_ALL_METADATA_SUCCESS = 'GET_ALL_METADATA_SUCCESS';
export const GET_ALL_METADATA_ERROR = 'GET_ALL_METADATA_ERROR';

export const GET_METADATA_BY_ID = 'GET_METADATA_BY_ID';
export const GET_METADATA_BY_ID_SUCCESS = 'GET_METADATA_BY_ID_SUCCESS';
export const GET_METADATA_BY_ID_ERROR = 'GET_METADATA_BY_ID_ERROR';

export const ADD_METADATA = 'ADD_METADATA';
