export const GET_METADATA_IDS = 'GET_METADATA_IDS';
export const GET_METADATA_IDS_SUCCESS = 'GET_METADATA_IDS_SUCCESS';
export const GET_METADATA_IDS_ERROR = 'GET_METADATA_IDS_ERROR';

export const GET_METADATAS_CONTENT = 'GET_METADATAS_CONTENT';
export const GET_METADATAS_CONTENT_SUCCESS = 'GET_METADATAS_CONTENT_SUCCESS';
export const GET_METADATAS_CONTENT_ERROR = 'GET_METADATAS_CONTENT_ERROR';

export const SET_CURRENT_METADATA = 'SET_CURRENT_METADATA';
export const SET_CURRENT_METADATA_SUCCESS = 'SET_CURRENT_METADATA_SUCCESS';
export const SET_CURRENT_METADATA_ERROR = 'SET_CURRENT_METADATA_ERROR';

export const ADD_METADATA = 'ADD_METADATA';
export const ADD_TEST_METADATA = 'ADD_TEST_METADATA';
