export const SET_APP_BACKGROUND = 'SET_APP_BACKGROUND';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const ADD_CARD_IMAGES = 'ADD_CARD_IMAGES';
export const ADD_ICON_IMAGE = 'ADD_ICON_IMAGE';
export const SET_CONTROLS = 'SET_CONTROLS';
