export const GET_METADATA_IDS = 'GET_METADATA_IDS';
export const GET_METADATA_IDS_SUCCESS = 'GET_METADATA_IDS_SUCCESS';
export const GET_METADATA_IDS_ERROR = 'GET_METADATA_IDS_ERROR';

export const LOAD_METADATAS = 'LOAD_METADATAS';
export const LOAD_METADATAS_SUCCESS = 'LOAD_METADATAS_SUCCESS';
export const LOAD_METADATAS_ERROR = 'LOAD_METADATAS_ERROR';

export const GET_METADATA_BY_ID = 'GET_METADATA_BY_ID';
export const GET_METADATA_BY_ID_SUCCESS = 'GET_METADATA_BY_ID_SUCCESS';
export const GET_METADATA_BY_ID_ERROR = 'GET_METADATA_BY_ID_ERROR';

export const ADD_METADATA = 'ADD_METADATA';
export const ADD_TEST_METADATA = 'ADD_TEST_METADATA';
