export const GET_POLICIES = 'GET_POLICIES';
export const GET_POLICIES_SUCCESS = 'GET_POLICIES_SUCCESS';
export const GET_POLICIES_ERROR = 'GET_POLICIES_ERROR';
export const POLICIES_NAMESPACE = 'policies';
