export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_ERROR = 'GET_PROJECTS_ERROR';
export const SET_PROJECTDETAIL_PAGE_BACK_URL = 'SET_PROJECTDETAIL_PAGE_BACK_URL';

export const PROJECTS_NAMESPACE = 'projects';
