
export const policies = {
  namespaced: true,
  policiesInfo: [
    { 
      title: 'Headline',
      text: 'FOREST FUNCTION DRINKING WATER FOREST FUNCTION GAME RESERVE FOREST FUNCTION LANDSCAPE PROTECTION FOREST FUNCTION MILITARY FOREST FUNCTION NATURE PROTECTION FOREST FUNCTION PROTECTION AGAINST NATURAL HAZARDS',
      bulletTitle: 'List title',
      bulletpoints: ['point 1', 'point2', 'point3'],
    },
    {
      title: 'Headline 2',
      text: 'FOREST FUNCTION DRINKING WATER FOREST FUNCTION GAME RESERVE FOREST FUNCTION LANDSCAPE PROTECTION FOREST FUNCTION MILITARY FOREST FUNCTION NATURE PROTECTION FOREST FUNCTION PROTECTION AGAINST NATURAL HAZARDS',
    },
    {
      title: 'Headline 3',
      text: 'FOREST FUNCTION DRINKING WATER FOREST FUNCTION GAME RESERVE FOREST FUNCTION LANDSCAPE PROTECTION FOREST FUNCTION MILITARY FOREST FUNCTION NATURE PROTECTION FOREST FUNCTION PROTECTION AGAINST NATURAL HAZARDS',
      bulletTitle: 'List title',
      bulletpoints: ['point 1', 'point2', 'point3'],
    },
  ],
  getters: {
    policiesInfo: state => state.policiesInfo,
  },
};
