export default [
  { name: 'AVALANCHE', enabled: true},
  { name: 'BIOGEOGRAPHICAL', enabled: true },
  { name: 'CLIMATE', enabled: true },
  { name: 'ECONOMIC', enabled: true },
  { name: 'FOREST', enabled: true },
  { name: 'HUMIDITY', enabled: true },
  { name: 'ICE', enabled: true },
  { name: 'LANDSLIDE', enabled: true },
  { name: 'LONG-TERM', enabled: true },
  { name: 'METEO', enabled: true },
  { name: 'PRECIPITATION', enabled: true },
  { name: 'ROCKFALL', enabled: true },
  { name: 'SNOW', enabled: true },
  { name: 'TEMPERATURE', enabled: true },
  { name: 'TREE', enabled: true },
  { name: 'VEGETATION', enabled: true },
  { name: 'WIND', enabled: true },
];
