export default [
  { name: 'AVALANCHE' },
  { name: 'BIOGEOGRAPHICAL' },
  { name: 'CLIMATE' },
  { name: 'ECONOMIC' },
  { name: 'FOREST' },
  { name: 'HUMIDITY' },
  { name: 'ICE' },
  { name: 'LANDSLIDE' },
  { name: 'LONG-TERM' },
  { name: 'METEO' },
  { name: 'PRECIPITATION' },
  { name: 'ROCKFALL' },
  { name: 'SNOW' },
  { name: 'TEMPERATURE' },
  { name: 'TREE' },
  { name: 'VEGETATION' },
  { name: 'WIND' },
];
